### ISSUE TITLE
update MOTD

### ISSUE THREAD

**Issue by Gjum** [CivClassic/Configs#2]
```json
{"text":"§3CivClassic SoonTM"}
```

**Comment by TealNerd** [comment]
?

**Comment by Gjum** [comment]
it's still saying `SoonTM` even though the server is live for weeks

**Comment by TealNerd** [comment]
Haha yeah it's a meme, I also don't know what to change it to, definitely open to suggestions

**Comment by MathInTheBath** [comment]
CivClassics: Build With More Than Just Autism

**Comment by Gjum** [comment]
![new MOTD](https://cdn.discordapp.com/attachments/280726458865942528/335029426687574018/unknown.png)
