### ISSUE TITLE
City Bastions need a recipe

### ISSUE THREAD

**Issue by Lazersmoke** [CivClassic/Configs#34]
See [here](https://github.com/CivClassic/Configs/blob/1e01e2a210cf80616fd43173004a780ca09f4c4d/FactoryMod/config.yml#L1484-L1533) for the current regular bastion recipe, and [here](https://github.com/CivClassic/Configs/blob/1e01e2a210cf80616fd43173004a780ca09f4c4d/Bastion/config.yml#L56-L61) for the current city bastion block and lore.

**Comment by TealNerd** [comment]
I was thinking either 1/4 or 1/8th cost

**Comment by Lazersmoke** [comment]
Resolved by #36
